package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// categoryOrder defines the set of valid "categories" values in info.json and
// the display order of map categories in the generated TypeScript.
var categoryOrder = []string{
	"featured",
	"world",
	"europe",
	"asia",
	"north_america",
	"africa",
	"south_america",
	"oceania",
	"antarctica",
	"cosmic",
	"tournament",
	"other",
}

// mapInfo is the subset of info.json fields used for code generation.
type mapInfo struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	TranslationKey string   `json:"translation_key"`
	Categories     []string `json:"categories"`
	// English display name written to en.json. Defaults to Name; set it when
	// the display name differs from the canonical (wire-format) name.
	DisplayName string `json:"display_name"`
	// How many times the map appears in the multiplayer playlist.
	// 0 (or omitted) keeps the map out of the regular rotation.
	MultiplayerFrequency int `json:"multiplayer_frequency"`
	// Position in the featured grid (1 = first). Featured maps without a
	// rank sort after ranked ones, alphabetically.
	FeaturedRank int `json:"featured_rank"`
	// Preferred team count in team/special games (see MapPlaylist).
	// 0 (or omitted) means no preference.
	SpecialTeamCount int `json:"special_team_count"`
}

// hasCategory reports whether the map lists the given category.
func (m mapInfo) hasCategory(category string) bool {
	for _, c := range m.Categories {
		if c == category {
			return true
		}
	}
	return false
}

// displayName returns the English display name for the map.
func (m mapInfo) displayName() string {
	if m.DisplayName != "" {
		return m.DisplayName
	}
	return m.Name
}

// loadMapInfos reads and validates every non-test map's info.json, in
// registry (alphabetical) order.
func loadMapInfos() ([]mapInfo, error) {
	inputDir, err := inputMapDir(false)
	if err != nil {
		return nil, err
	}

	infos := make([]mapInfo, 0, len(maps))
	for _, m := range maps {
		if m.IsTest {
			continue
		}
		buf, err := os.ReadFile(filepath.Join(inputDir, m.Name, "info.json"))
		if err != nil {
			return nil, fmt.Errorf("failed to read info.json for %s: %w", m.Name, err)
		}
		var info mapInfo
		if err := json.Unmarshal(buf, &info); err != nil {
			return nil, fmt.Errorf("failed to parse info.json for %s: %w", m.Name, err)
		}
		if info.ID == "" || strings.ToLower(info.ID) != m.Name {
			return nil, fmt.Errorf("map %s: info.json \"id\" (%q) must be the folder name in UpperCamelCase", m.Name, info.ID)
		}
		if info.Name == "" {
			return nil, fmt.Errorf("map %s: info.json is missing \"name\"", m.Name)
		}
		if info.TranslationKey != "map."+m.Name {
			return nil, fmt.Errorf("map %s: info.json \"translation_key\" (%q) must be %q", m.Name, info.TranslationKey, "map."+m.Name)
		}
		if info.MultiplayerFrequency < 0 {
			return nil, fmt.Errorf("map %s: info.json \"multiplayer_frequency\" (%d) must be >= 0", m.Name, info.MultiplayerFrequency)
		}
		if info.FeaturedRank < 0 {
			return nil, fmt.Errorf("map %s: info.json \"featured_rank\" (%d) must be >= 1", m.Name, info.FeaturedRank)
		}
		if info.FeaturedRank > 0 && !info.hasCategory("featured") {
			return nil, fmt.Errorf("map %s: info.json sets \"featured_rank\" but \"categories\" does not include \"featured\"", m.Name)
		}
		if info.SpecialTeamCount < 0 || info.SpecialTeamCount == 1 {
			return nil, fmt.Errorf("map %s: info.json \"special_team_count\" (%d) must be >= 2", m.Name, info.SpecialTeamCount)
		}
		if len(info.Categories) == 0 {
			return nil, fmt.Errorf("map %s: info.json \"categories\" must list at least one category", m.Name)
		}
		seen := make(map[string]bool)
		for _, category := range info.Categories {
			valid := false
			for _, c := range categoryOrder {
				if category == c {
					valid = true
					break
				}
			}
			if !valid {
				return nil, fmt.Errorf("map %s: info.json category %q must be one of: %s", m.Name, category, strings.Join(categoryOrder, ", "))
			}
			if seen[category] {
				return nil, fmt.Errorf("map %s: info.json lists category %q more than once", m.Name, category)
			}
			seen[category] = true
		}
		infos = append(infos, info)
	}
	return infos, nil
}

// generateMapsTS writes the GameMapType enum, the MapCategory union, the
// MapInfo interface, and the maps list to src/core/game/Maps.gen.ts.
// Derived lookups (mapCategories, mapTranslationKeys, ...) live in Game.ts.
func generateMapsTS(infos []mapInfo) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}
	outPath := filepath.Join(cwd, "..", "src", "core", "game", "Maps.gen.ts")

	var b strings.Builder
	b.WriteString("// Code generated by map-generator; DO NOT EDIT.\n")
	b.WriteString("// Map metadata lives in map-generator/assets/maps/<map>/info.json.\n")
	b.WriteString("// Regenerate with `npm run gen-maps`.\n\n")

	b.WriteString("export enum GameMapType {\n")
	for _, info := range infos {
		// Trailing comment so editors can jump straight to the map's info.json.
		b.WriteString(fmt.Sprintf("  %s = %q, // map-generator/assets/maps/%s/info.json\n",
			info.ID, info.Name, strings.ToLower(info.ID)))
	}
	b.WriteString("}\n\n")

	b.WriteString("export type GameMapName = keyof typeof GameMapType;\n\n")

	b.WriteString("export type MapCategory =\n")
	for i, category := range categoryOrder {
		sep := "\n"
		if i == len(categoryOrder)-1 {
			sep = ";\n\n"
		}
		b.WriteString(fmt.Sprintf("  | %q%s", category, sep))
	}

	b.WriteString("// Category display order in the map picker.\n")
	b.WriteString("export const mapCategoryOrder: readonly MapCategory[] = [\n")
	for _, category := range categoryOrder {
		b.WriteString(fmt.Sprintf("  %q,\n", category))
	}
	b.WriteString("];\n\n")

	b.WriteString("export interface MapInfo {\n")
	b.WriteString("  /** GameMapType enum key — the UpperCamelCase folder name. */\n")
	b.WriteString("  id: GameMapName;\n")
	b.WriteString("  /** Canonical map name (wire format) — the GameMapType enum value. */\n")
	b.WriteString("  type: GameMapType;\n")
	b.WriteString("  /** Key of the map's display name in resources/lang/en.json. */\n")
	b.WriteString("  translationKey: string;\n")
	b.WriteString("  /** Map picker categories. */\n")
	b.WriteString("  categories: MapCategory[];\n")
	b.WriteString("  /** How many times the map appears in the multiplayer playlist. */\n")
	b.WriteString("  multiplayerFrequency: number;\n")
	b.WriteString("  /** Position in the featured grid (1 = first); unranked featured maps sort last. */\n")
	b.WriteString("  featuredRank?: number;\n")
	b.WriteString("  /** Preferred team count in team/special games (see MapPlaylist). */\n")
	b.WriteString("  specialTeamCount?: number;\n")
	b.WriteString("}\n\n")

	b.WriteString("export const maps: readonly MapInfo[] = [\n")
	for _, info := range infos {
		b.WriteString("  {\n")
		b.WriteString(fmt.Sprintf("    id: %q,\n", info.ID))
		b.WriteString(fmt.Sprintf("    type: GameMapType.%s,\n", info.ID))
		b.WriteString(fmt.Sprintf("    translationKey: %q,\n", info.TranslationKey))
		b.WriteString("    categories: [")
		for i, category := range info.Categories {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", category))
		}
		b.WriteString("],\n")
		b.WriteString(fmt.Sprintf("    multiplayerFrequency: %d,\n", info.MultiplayerFrequency))
		if info.FeaturedRank > 0 {
			b.WriteString(fmt.Sprintf("    featuredRank: %d,\n", info.FeaturedRank))
		}
		if info.SpecialTeamCount > 0 {
			b.WriteString(fmt.Sprintf("    specialTeamCount: %d,\n", info.SpecialTeamCount))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("];\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", outPath, err)
	}
	return nil
}

// generateEnJSON rewrites the "map" section of resources/lang/en.json with
// each map's display name, keyed by folder name. Existing keys in the
// section that are not maps (e.g. "featured", "random") are preserved, in
// their original order, ahead of the map entries.
//
// The file is parsed as a sequence of top-level (key, raw value) pairs —
// json.Decoder preserves encounter order and json.RawMessage keeps every
// other section byte-for-byte, so only the "map" object changes.
func generateEnJSON(infos []mapInfo) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}
	enPath := filepath.Join(cwd, "..", "resources", "lang", "en.json")
	content, err := os.ReadFile(enPath)
	if err != nil {
		return fmt.Errorf("failed to read en.json: %w", err)
	}

	type section struct {
		key string
		raw json.RawMessage
	}
	var sections []section
	mapIndex := -1

	dec := json.NewDecoder(strings.NewReader(string(content)))
	if _, err := dec.Token(); err != nil { // opening brace
		return fmt.Errorf("failed to parse en.json: %w", err)
	}
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return fmt.Errorf("failed to parse en.json: %w", err)
		}
		key, ok := keyTok.(string)
		if !ok {
			return fmt.Errorf("unexpected token %v at the top level of en.json", keyTok)
		}
		var raw json.RawMessage
		if err := dec.Decode(&raw); err != nil {
			return fmt.Errorf("failed to parse en.json %q section: %w", key, err)
		}
		if key == "map" {
			mapIndex = len(sections)
		}
		sections = append(sections, section{key, raw})
	}
	if mapIndex < 0 {
		return fmt.Errorf("en.json has no top-level \"map\" section")
	}

	// Walk the existing map section in order, keeping non-map entries.
	mapFolders := make(map[string]bool, len(infos))
	for _, info := range infos {
		mapFolders[strings.ToLower(info.ID)] = true
	}
	type entry struct{ key, value string }
	var entries []entry
	mapDec := json.NewDecoder(strings.NewReader(string(sections[mapIndex].raw)))
	if _, err := mapDec.Token(); err != nil { // opening brace
		return fmt.Errorf("failed to parse the \"map\" section in en.json: %w", err)
	}
	for mapDec.More() {
		keyTok, err := mapDec.Token()
		if err != nil {
			return fmt.Errorf("failed to parse the \"map\" section in en.json: %w", err)
		}
		key, ok := keyTok.(string)
		if !ok {
			return fmt.Errorf("unexpected token %v in the \"map\" section of en.json", keyTok)
		}
		var value string
		if err := mapDec.Decode(&value); err != nil {
			return fmt.Errorf("en.json map.%s: expected a string value: %w", key, err)
		}
		if !mapFolders[key] {
			entries = append(entries, entry{key, value})
		}
	}
	for _, info := range infos {
		entries = append(entries, entry{strings.ToLower(info.ID), info.displayName()})
	}

	var mapSection strings.Builder
	mapSection.WriteString("{")
	for i, e := range entries {
		if i > 0 {
			mapSection.WriteString(",")
		}
		mapSection.WriteString(fmt.Sprintf("\n    %s: %s", jsonString(e.key), jsonString(e.value)))
	}
	mapSection.WriteString("\n  }")
	sections[mapIndex].raw = json.RawMessage(mapSection.String())

	var b strings.Builder
	b.WriteString("{\n")
	for i, s := range sections {
		if i > 0 {
			b.WriteString(",\n")
		}
		b.WriteString(fmt.Sprintf("  %s: %s", jsonString(s.key), s.raw))
	}
	b.WriteString("\n}\n")

	if err := os.WriteFile(enPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write en.json: %w", err)
	}
	return nil
}

// jsonString encodes s as a JSON string literal without HTML escaping.
func jsonString(s string) string {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(s); err != nil {
		panic(err) // strings always encode
	}
	return strings.TrimRight(b.String(), "\n")
}
