import type { PlayerStats } from "@openfront/engine-api/StatsSchemas";
import { XpRulesSchema } from "@openfront/shared/ApiSchemas";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  computeXp,
  ffaOutlasted,
  PROVISIONAL_XP_FORMULA,
  type XpContext,
} from "../../src/client/ProvisionalXp";

// Cases generated by the API from its own computeXp (lib/progression/Xp.ts):
// the client's copy must return exactly what the server would, line for
// line. Bigints are decimal strings; a player who never spawned has
// `stats: null`. A case with its own `rules` is scored with those instead
// of the file's (feats pay 0 by default, so their cases also run with
// featXp > 0).
interface ReferenceCase {
  name: string;
  ctx: Omit<XpContext, "stats"> & { stats: unknown };
  rules?: unknown;
  expected: unknown;
}
const reference = JSON.parse(
  readFileSync(
    join(__dirname, "../testdata/progression/xp-reference-cases.json"),
    "utf8",
  ),
) as {
  formula: number;
  configVersion: number;
  rules: unknown;
  cases: ReferenceCase[];
};

// Stats as the game holds them: every decimal string a bigint.
function reviveStats(value: unknown): unknown {
  if (typeof value === "string" && /^-?\d+$/.test(value)) return BigInt(value);
  if (Array.isArray(value)) return value.map(reviveStats);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, reviveStats(v)]),
    );
  }
  return value;
}

function contextOf(c: ReferenceCase): XpContext {
  return {
    ...c.ctx,
    stats:
      c.ctx.stats === null
        ? undefined
        : (reviveStats(c.ctx.stats) as PlayerStats),
  };
}

describe("provisional XP: the API's reference cases", () => {
  const rules = XpRulesSchema.parse(reference.rules);

  it("are for the formula revision this client carries", () => {
    expect(reference.formula).toBe(PROVISIONAL_XP_FORMULA);
    expect(reference.cases.length).toBeGreaterThan(0);
  });

  it("cover the first game of the day, and feats that pay", () => {
    const totals = (pred: (c: ReferenceCase) => boolean) =>
      reference.cases.filter(pred).length;
    const firstGame = (c: ReferenceCase) =>
      (c.expected as { breakdown?: { firstGame: number } }).breakdown
        ?.firstGame ?? 0;
    expect(
      totals((c) => firstGame(c) === rules.firstGameOfDay),
    ).toBeGreaterThan(0);
    expect(
      totals((c) => c.ctx.daily.firstGameClaimed && firstGame(c) === 0),
    ).toBeGreaterThan(0);
    expect(
      totals(
        (c) =>
          c.rules !== undefined &&
          ((c.expected as { breakdown?: { feats: number } }).breakdown?.feats ??
            0) > 0,
      ),
    ).toBeGreaterThan(0);
  });

  it.each(reference.cases.map((c) => [c.name, c] as const))(
    "%s",
    (_name, c) => {
      const own = c.rules === undefined ? rules : XpRulesSchema.parse(c.rules);
      expect(computeXp(contextOf(c), own)).toEqual(c.expected);
    },
  );
});

describe("ffaOutlasted", () => {
  const stats = (s: Record<string, bigint>): PlayerStats => s;

  it("counts the opponents who went out strictly before each player", () => {
    const out = ffaOutlasted(
      [
        { clientID: "a", stats: stats({ killedAt: 3000n }) },
        { clientID: "b", stats: stats({ killedAt: 2000n }) },
        { clientID: "c", stats: stats({ killedAt: 2000n }) },
        { clientID: "d", stats: stats({}) },
        { clientID: "never", stats: undefined },
      ],
      5000,
    );
    expect(Object.fromEntries(out)).toEqual({ a: 2, b: 0, c: 0, d: 3 });
  });

  it("puts a player who left out at the tick they left", () => {
    const out = ffaOutlasted(
      [
        { clientID: "me", stats: stats({ killedAt: 3000n }) },
        { clientID: "quit", stats: stats({}) },
        { clientID: "late", stats: stats({}) },
      ],
      5000,
      new Map([
        ["quit", 1000],
        ["late", 4000],
      ]),
    );
    expect(out.get("me")).toBe(1);
  });
});
