// Code generated by map-generator; DO NOT EDIT.
// Map metadata lives in map-generator/assets/maps/<map>/info.json.
// Regenerate with `npm run gen-maps`.
// NOTE: This fork is Europe-only — all other maps have been removed.

export enum GameMapType {
  Europe = "Europe", // map-generator/assets/maps/europe/info.json
}

export type GameMapName = keyof typeof GameMapType;

export type MapCategory =
  | "featured"
  | "new"
  | "world"
  | "continental"
  | "europe"
  | "asia"
  | "north_america"
  | "africa"
  | "south_america"
  | "oceania"
  | "antarctica"
  | "countries"
  | "cosmic"
  | "fictional"
  | "arcade"
  | "tournament";

// Category display order in the map picker.
export const mapCategoryOrder: readonly MapCategory[] = [
  "featured",
  "new",
  "world",
  "continental",
  "europe",
  "asia",
  "north_america",
  "africa",
  "south_america",
  "oceania",
  "antarctica",
  "countries",
  "cosmic",
  "fictional",
  "arcade",
  "tournament",
];

export interface MapInfo {
  /** GameMapType enum key — the UpperCamelCase folder name. */
  id: GameMapName;
  /** Canonical map name (wire format) — the GameMapType enum value. */
  type: GameMapType;
  /** Key of the map's display name in resources/lang/en.json. */
  translationKey: string;
  /** Map picker categories. */
  categories: MapCategory[];
  /** How many times the map appears in the multiplayer playlist. */
  multiplayerFrequency: number;
  /** Position in the featured grid (1 = first); unranked featured maps sort last. */
  featuredRank?: number;
  /** Preferred team count in team/special games (see MapPlaylist). */
  specialTeamCount?: number;
  /** Tribe name theme(s) (keys in tribeNameThemes.json). */
  themes?: string[];
  /** Custom tribe entry: a string (random spawn) or an object with name and coordinates. */
  customTribes?: CustomTribe[];
}

export interface CustomTribe {
  name: string;
  coordinates?: [number, number];
}

export const maps: readonly MapInfo[] = [
  {
    id: "Europe",
    type: GameMapType.Europe,
    translationKey: "map.europe",
    categories: ["featured", "continental", "europe"],
    multiplayerFrequency: 7,
    featuredRank: 2,
  },
];
